### PR TITLE
Feature/clean+massiveaction

### PR DESCRIPTION
**Pull request by orthagh**

### CODE REVIEW

**Comment by orthagh** [comment]
Currently WIP

**Comment by orthagh** [comment]
added issues to close after merge

**Comment by orthagh** [comment]
Ok, completely done.
This PR is huge, it's a kind of full rewrite, but here is a detail
- clean dead code
- review CS
- remove french (and strange) comments
- use modern glpi hooks (pre_item_form, getSpecificValueTo[Select|Display])
- move wall of code from setup.php in respective classes
- massive actions for add/delete tags
- use add_item hook to permit adding an item and his tags (previously possible only on update)
- change min version of glpi

**Comment by orthagh** [comment]
@trasher i'm done with this PR, if you could check it (and plan a release)

Many thanks.

**Comment by trasher** [comment]
@orthagh OK, I'll take a look next week ;)

**Comment by trasher** [comment]
A few comments:
- display is not consistent with what we can see elsewhere (border only displayed on hover, drowdown size smaller than input, hover on dropdown like a bit strange ...)
- "view all tags" points to form instead of tags list
- when adding a tag on computers, this is added in both main form and OS form
- tag removal does not work (display "0")
- query errors when adding a new item (new compute,r new phone, ...)
- notices on tag search

**Comment by orthagh** [comment]
> display is not consistent with what we can see elsewhere (border only displayed on hover, drowdown size smaller than input, hover on dropdown like a bit strange ...)

fixed

> "view all tags" points to form instead of tags list

fixed

> when adding a tag on computers, this is added in both main form and OS form

This one is difficult to avoid.
pre_item_form hook send Computer item for both tabs.
Do you have hint for that ?

> tag removal does not work (display "0")

fixed

> query errors when adding a new item (new compute,r new phone, ...)

fixed

> notices on tag search

I didn't found this one, any pointer ?

**Comment by orthagh** [comment]
> when adding a tag on computers, this is added in both main form and OS form
>> This one is difficult to avoid.
>> pre_item_form hook send Computer item for both tabs.
>> Do you have hint for that ?

Finally found a way by checking fields plugin code

**Comment by trasher** [comment]
Ok for all the fixes.

As for the search notice; I've created a tag I've added on a computer. From computer list, searching on "Tag" "Contains" "{value}" gives:
```
==> /var/www/webapps/glpi/files/_log/php-errors.log <==
2017-02-20 12:47:00 [2@LF014]
  *** PHP Notice(8): Undefined variable: ID
  Backtrace :
  plugins/tag/hook.php:121                           
  inc/search.class.php:1974                          plugin_tag_addHaving()
  inc/search.class.php:472                           Search::addHaving()
  inc/search.class.php:97                            Search::constructSQL()
  inc/search.class.php:81                            Search::showList()
  front/computer.php:43                              Search::show()
2017-02-20 12:47:00 [2@LF014]
  *** PHP Notice(8): Undefined index: 
  Backtrace :
  plugins/tag/hook.php:121                           
  inc/search.class.php:1974                          plugin_tag_addHaving()
  inc/search.class.php:472                           Search::addHaving()
  inc/search.class.php:97                            Search::constructSQL()
  inc/search.class.php:81                            Search::showList()
  front/computer.php:43                              Search::show()
2017-02-20 12:47:00 [2@LF014]
  *** PHP Notice(8): Undefined variable: ID
  Backtrace :
  plugins/tag/hook.php:122                           
  inc/search.class.php:1974                          plugin_tag_addHaving()
  inc/search.class.php:472                           Search::addHaving()
  inc/search.class.php:97                            Search::constructSQL()
  inc/search.class.php:81                            Search::showList()
  front/computer.php:43                              Search::show()
2017-02-20 12:47:00 [2@LF014]
  *** PHP Notice(8): Undefined index: 
  Backtrace :
  plugins/tag/hook.php:122                           
  inc/search.class.php:1974                          plugin_tag_addHaving()
  inc/search.class.php:472                           Search::addHaving()
  inc/search.class.php:97                            Search::constructSQL()
  inc/search.class.php:81                            Search::showList()
  front/computer.php:43                              Search::show()
```

**Comment by orthagh** [comment]
Done

**Comment by orthagh** [comment]
merged

**Pull request closed without merging**
