### PR TITLE
Remove unnecessary tag purges

### PR DESCRIPTION
**Pull request by iZlovreD**
Each time when new tag added to the items all existed tags deleted and then restored with new ones. Same with deletion - all tags removed and then restore only those which must stay.

### CODE REVIEW

**Review by cedric-anne — COMMENTED** [review]
Unless I am wrong, it will break the "Add tag" massive action. Indeed, in cas of massive actions `delete_old` was set to false as only the added tag was passed to this method.

**Comment by iZlovreD** [comment]
> Unless I am wrong, it will break the "Add tag" massive action. Indeed, in cas of massive actions `delete_old` was set to false as only the added tag was passed to this method.

Yes. I haven't checked this. But, we can easily solve this issue by adding checking on the "delete_tag" field in the options variable at 372 line.
`if (!isset($options['delete_old']) || $options['delete_old'])
         foreach ($tag_del as $tag_id) {`

**Comment by iZlovreD** [comment]
The point is that there would be no unnecessary triggering of hooks. So that when the tag deletion hook is triggered, this is exactly the deletion, and not the preliminary cleaning. And accordingly, when the add hook is triggered, this is not the restoration of previously existing ones.

**Comment by cedric-anne** [comment]
Hi,

Thanks for the contribution :+1: . I cherry-picked your commits refactored a little the code to make it more clear (at my opinion at least).
Fix is present in 2.8.2 release.

Regards

**Pull request closed without merging**
